CREATE CACHED TABLE PUBLIC.WEIGHT(
    ID INT AUTO_INCREMENT,
    DATE DATE NOT NULL,
    KILOGRAMS FLOAT8 NOT NULL,
    USER_ID INT 
);
ALTER TABLE PUBLIC.WEIGHT ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID);
ALTER TABLE PUBLIC.WEIGHT ADD CONSTRAINT PUBLIC.UK_R4KY9E01CP3060J1HGMMQO220 UNIQUE(USER_ID, DATE);


CREATE CACHED TABLE PUBLIC.FITNESS_USER(
    ID INT AUTO_INCREMENT,
    ACTIVITY_LEVEL FLOAT8 NOT NULL,
    BIRTHDATE DATE NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL,
    GENDER VARCHAR(6) NOT NULL,
    HEIGHT_IN_CM FLOAT8 NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    LAST_UPDATED_TIME TIMESTAMP NOT NULL,
    PASSWORD_HASH VARCHAR(100),
    TIMEZONE VARCHAR(50) NOT NULL DEFAULT 'America/New_York'
);
ALTER TABLE PUBLIC.FITNESS_USER ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);

ALTER TABLE PUBLIC.WEIGHT ADD CONSTRAINT PUBLIC.FK_RUS9MPSDMIJSL6FUJHHUD5PGU FOREIGN KEY(USER_ID) REFERENCES PUBLIC.FITNESS_USER(ID) NOCHECK;

